apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops
spec:
  accessModes:
    ReadWriteMany
  storageClassName: standard
  resource:
    requests:
      storage: 5Gi
