apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: devops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-cr
rules:
  - apiGroup: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
  - apiGroup: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
  - apiGroup: [ "" ]
    resources: [ "pods" ]
    verbs: [ "create", "delete", "get", "list", "watch", "patch", "update" ]
  - apiGroup: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create", "delete", "get", "list", "watch", "patch", "update" ]
  - apiGroup: [ "" ]
    resources: [ "pods/logs" ]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-crb
RoleRef:
  kind: ClusterRole
  name: jenkins-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: devops
    
  
