# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  # LowercaseLevelEncoder:小写, LowercaseColorLevelEncoder:小写带颜色,CapitalLevelEncoder: 大写, CapitalColorLevelEncoder: 大写带颜色,
  encode-level: 'CapitalLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql configuration
mysql:
#  path: '192.168.210.253:3318'
  path: 'rm-uf6vr2e018e95e4hz6o.mysql.rds.aliyuncs.com'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'luban'
#  username: 'dev'
#  password: 'dev123456'
  username: 'root'
  password: 'Sy122812'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""

# casbin configuration
casbin:
  model-path: './etc/rbac_model.conf'

# system configuration
system:
  env: 'private'  # Change to "develop" to skip authentication for development mode,  change to "private" authentication
  addr: 8999
  db-type: 'mysql'


redis:
#  host: '192.168.206.223:6379'
  host: '47.94.96.190:6379'
  db: 0
#  username: '223'
#  password: 'publish'
  username: ''
  password: ''
# cloudSync Task
crontab:
  aliyun: "00 */2 * * *"