apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: es-allresource
  namespace: rbac
subject:
  - kind: User
    name: es
    apiGroup: rbac.authorization.k8s.io       #  常见的角色绑定示例
  RoleRef:
    - kind: ClusterRole
      name: secrets-clusterrole
      apiGroup: rbac.authorization.k8s.io
    

