apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        containers:
          -name: hello
          image: busybox
          command: ["bin/bash", "-c", "date;echo hello"]
        restartPolicy: OnFailure


