apiVersion: v1
kind: ReplicationController
metadata:
  name: roll-v2
  labels:
    name: roll-v2
    version: v2
spec:
  replicas: 3
  selector:
    name: roll-v2
    version: v2
  template:
    metadata:
      name: roll-v2
      version: v2
    spec:
      containers:
        -name: roll-v2
        image: nginx
        imagePullPolicy: IfNotPersent
        ports:
          containerPort: 8080
        