apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress
  namespace: ingress
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-ingress
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: ingress-sc
      containers:
        -name: nginx-ingress
        image: images/nginx-ingress-controller:0.32.0
        imagePullPolicy: IfNotPersent
        env:
          -name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 80
            hostPort: 80
          
          - containerPort: 443
            hostPort: 443
      
