apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: rbac
spec:
  serviceAccountName: pod-reader-sc # pod的权限，赋值为pod-reader-sc 这个角色的权限
  hostNetWork: True
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: iFNotPersent
      ports:
        containersPort:80
        hostPort:80
        nodePort: 80


kubectl create  rolebinding my-sa-view --clusterrole=view --serviceaccount=my-namespace:my-sa --namespace=my-namespace
kubectl create rolebinding default-view --clusterrole=view --serviceaccount=my-namespace:default --namespace=my-namespace
kubectl create clusterrolebinding add-ons-add-admin --clusterrole=cluster-admim --serviceaccount=kube-system:default
kubectl create rolebinding serviceaccount-view --cluserrole=view --group=system:serviceaccount:my-namespace --namespace=my-namespace
kubectl create cluserrolebinding serviceaccount-view --clusterrole=view --group=system:serviceaccount
kubectl create clusterrolebinding serviceaccount-view --clusterrolr=cluster-admin --group=system:serviceaccount
kubectl create rolebinding bob-admin-view --clusterrole=admin --user=es --namespace=rbac
kubectl create rolebinding myapp-role-binding --clusterrole=view --serviceaccount=acme:myapp --namespace=rbac
kubectl create clusterrolebinding cluster-binding  --cluserrole=cluster-admin --user=root
kubectl create clusterrolebinding service-account-binding --clusterrole=view --serviceaccount=acme:myapp


      