apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: pod
      image: image
      volumeMounts:
        -name: foo
        mountPath: "/data"
        readOnly: true
  volumes:
    - name: foo
      secret:
        sercetname: sercetname


        