apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:pv
  labels:
    name: nginx
spec:
  containers:
    -name: nginx
    image: nginx
    imagePullPolicy: IfNotPersent
    volumeMounts:
      -name: pv
      mountPath: /pvc
      readOnly: false
    ports:
      - containerPort: 80
  volumes:
    -name: pv
     persisentVolumeClaim:
       claimName: pvc

# 共享
    
  