apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    name: nginx-pod
spec:
  hostNetWork: true   # 以为容器端口必须与 宿主机端口一致
  containers:
    -name: nginx-pod2
    image: nginx
    imagePullPolicy: IfNotPersent
    ports:
      - containerPort: 80
        hostPort: 80 # 可以缺省