# kubectl rolling-update roll-v1 -f nginx-v2.yaml
# kubelctl rolling-update rc-name --image=image-name:version         直接替换镜像升级
# kubectl rolling-update rc-name --imag=image-name:version --rollback        回滚
apiVersion: v1
kind: ReplicationController
metadata:
  name: roll-v1
  labels:
    name: roll-v1
    version: v1
spec:
  replicas: 3
  selector:
    name: roll-v1
    version: v1
  template:
    metadata:
      name: roll-v1
      labels:
        name: roll-v1
        version: v1
    spec:
      containers:
        - name: roll-v1
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80