apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: pv
  labels:
    name: pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReClaimPolicy: Recycle
  hostpath:
    path: /usr/soft/k8s/yaml/pv/storage
    
  

