apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac
  name: pod-read
rules:
  - apiGroups: [""]
    resource: ["pods"] # pods, deployments, jobs
    resourceName: []
    verbs: ["get","watch","list"]